name: Keep Alive Supabase CSDL PHAN MEM KIEM TRA TRUC TUYEN

on:
  schedule:
    - cron: '0 * * * *' # Chạy tự động mỗi 1 giờ (phút thứ 0)
  workflow_dispatch:      # Cho phép bạn bấm nút chạy thủ công để kiểm tra

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Insert Time into Supabase DB directly
        run: |
          # Gửi REST API Request POST thẳng vào DataBase tới bảng 'duytricsdl' kèm thời gian chuẩn Việt Nam
          curl -X POST "https://jfmblflvhrwzlzebpvjl.supabase.co/rest/v1/duytricsdl" \
            -H "apikey: sb_publishable_fMfzYhcZj2UOF8jLSRqVbw_48dCsaiS" \
            -H "Authorization: Bearer sb_publishable_fMfzYhcZj2UOF8jLSRqVbw_48dCsaiS" \
            -H "Content-Type: application/json" \
            -d "{\"thoigian\": \"$(TZ='Asia/Ho_Chi_Minh' date +'%Y-%m-%dT%H:%M:%S+07:00')\"}"
          echo "Đã chủ động nối máy và ghi nhật ký thời gian lúc: $(TZ='Asia/Ho_Chi_Minh' date)"
